- hosts: all
  become: yes
  vars:
    user: vagrant
  tasks:
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Add docker key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add docker repo
      apt_repository: repo='deb [arch=amd64] http://download.docker.com/linux/ubuntu disco stable' state=present

    - name: Add heroku key
      apt_key: url=https://cli-assets.heroku.com/apt/release.key state=present

    - name: Add heroku repo
      apt_repository: repo='deb http://cli-assets.heroku.com/branches/stable/apt ./' state=present

    - name: Add cdh6 key
      apt_key: url=https://archive.cloudera.com/cdh6/6.3.2/ubuntu1804/apt/archive.key

    - name: Add cdh6 repo
      apt_repository: repo='deb [arch=amd64] https://archive.cloudera.com/cdh6/6.3.2/ubuntu1804/apt bionic-cdh6.3.2 contrib' state=present

    - name: Install packages
      apt:
        state: present
        update_cache: yes
        force_apt_get: true
        name:
          - language-pack-ja
          - ntp
          - zsh
          - screen
          - npm
          - emacs-nox
          - silversearcher-ag
          - mysql-server
          - postgresql
          - redis-server
          - imagemagick
          - net-tools
          - python-pip
          - python-psycopg2
          - libxml2-dev
          - libmagick++-dev
          - libmysql++-dev
          - libpq-dev
          - libssl-dev
          - libreadline-dev
          - libcurl4-openssl-dev
          - docker-ce
          - heroku
          - hadoop-conf-pseudo
          - hive
          - hive-metastore
          - hive-server2
          - libpostgresql-jdbc-java

    - name: Add docker group
      user: name={{user}} append=yes groups=docker

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: namenode directory check
      stat:
        path: /var/lib/hadoop-hdfs/cache/hdfs/dfs/name
      register: namenode

    - name: hdfs namenode -format
      become_user: hdfs
      command: hdfs namenode -format
      when: namenode.stat.exists == false

    - name: Create postgresql hive user
      become_user: postgres
      postgresql_user:
        name: hive
        password: password
        role_attr_flags: SUPERUSER,LOGIN

    - name: Create a new database with name metastore
      become_user: postgres
      postgresql_db:
        name: metastore

    - name: Copy hive-site.xml
      copy: src=./hive-site.xml dest=/etc/hive/conf/hive-site.xml owner=root group=root mode=0644

    - name: Create postgresql jdbc driver symbolic link
      file: src=/usr/share/java/postgresql.jar dest=/usr/lib/hive/lib/postgresql.jar state=link

    - name: Shell login hive user
      user: name=hive groups=hive shell=/bin/bash append=yes

    - name: Set authorized key for user vagrant copying it from user hive
      authorized_key: user=hive key={{lookup('file', '/home/{{user}}/.ssh/authorized_keys')}} state=present

    - name: Start services
      action: service name={{item}} state=started enabled=yes
      with_items:
        - mysql
        - postgresql
        - redis
        - docker
        - postgresql
        - hadoop-hdfs-namenode
        - hadoop-hdfs-datanode
        - hadoop-hdfs-secondarynamenode
        - hadoop-yarn-resourcemanager
        - hadoop-yarn-nodemanager
        - hive-metastore
        - hive-server2

    - name: Install awscli
      pip: name=awscli state=present

    - name: Install yarn
      npm: name=yarn global=yes state=present

    - name: Install docker-clean
      npm: name=docker-clean global=yes state=present

    - name: Install rbenv
      become_user: '{{user}}'
      git: repo=https://github.com/rbenv/rbenv.git dest=/home/{{user}}/.rbenv accept_hostkey=yes

    - name: Install ruby-build
      become_user: '{{user}}'
      git: repo=https://github.com/rbenv/ruby-build.git dest=/home/{{user}}/.rbenv/plugins/ruby-build accept_hostkey=yes

    - name: Install nodenv
      become_user: '{{user}}'
      git: repo=https://github.com/nodenv/nodenv.git dest=/home/{{user}}/.nodenv accept_hostkey=yes

    - name: Install node-build
      become_user: '{{user}}'
      git: repo=https://github.com/nodenv/node-build.git dest=/home/{{user}}/.nodenv/plugins/nodenv-build accept_hostkey=yes

    - name: Execute chsh zsh
      command: chsh {{user}} -s /bin/zsh

    - name: Execute git clone dotfiles
      become_user: '{{user}}'
      git: repo=https://github.com/f96q/dotfiles.git dest=/home/{{user}}/dotfiles accept_hostkey=yes

    - name: Setup dotfiles
      become_user: '{{user}}'
      command: bash setup.sh chdir=/home/{{user}}/dotfiles

    - name: Allow Empty mysql root password
      command: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"

    - name: Create postgresql vagrant user
      become_user: postgres
      postgresql_user:
        name: vagrant
        role_attr_flags: SUPERUSER,LOGIN
