- hosts: all
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Add docker key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add docker repo
      apt_repository: repo='deb [arch=amd64] http://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable' state=present

    - name: Install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - language-pack-ja
        - zsh
        - screen
        - emacs-nox
        - silversearcher-ag
        - mysql-server
        - redis-server
        - elasticsearch
        - imagemagick
        - ruby
        - ruby-dev
        - nodejs
        - nodejs-legacy
        - phantomjs
        - python-pip
        - libxml2-dev
        - libmagick++-dev
        - libmysql++-dev
        - libpq-dev
        - docker-ce

    - name: Add docker group
      user: name={{user}} append=yes groups=docker

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Start services
      action: service name={{item}} state=started enabled=yes
      with_items:
        - mysql
        - redis
        - elasticsearch
        - docker

    - name: Install awscli
      command: pip install awscli

    - name: Install bundler
      command: gem install bundler

    - name: Execute chsh zsh
      command: chsh ubuntu -s /bin/zsh

    - name: Execute git clone dotfiles
      become_user: '{{user}}'
      git: repo=https://github.com/f96q/dotfiles.git dest=/home/{{user}}/dotfiles accept_hostkey=yes

    - name: Setup dotfiles
      become_user: '{{user}}'
      command: bash setup.sh chdir=/home/{{user}}/dotfiles
