- hosts: all
  become: yes
  vars:
    user: vagrant
  tasks:
    - name: Set timezone
      timezone: name=Asia/Tokyo

    - name: Add docker key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add docker repo
      apt_repository: repo='deb [arch=amd64] http://download.docker.com/linux/ubuntu disco stable' state=present

    - name: Add heroku key
      apt_key: url=https://cli-assets.heroku.com/apt/release.key state=present

    - name: Add heroku repo
      apt_repository: repo='deb http://cli-assets.heroku.com/branches/stable/apt ./' state=present

    - name: Install packages
      apt:
        state: present
        update_cache: yes
        force_apt_get: true
        name:
          - language-pack-ja
          - chrony
          - zsh
          - screen
          - npm
          - emacs-nox
          - silversearcher-ag
          - mysql-server
          - postgresql
          - redis-server
          - imagemagick
          - net-tools
          - python-pip
          - python-psycopg2
          - libxml2-dev
          - libmagick++-dev
          - libmysql++-dev
          - libpq-dev
          - libssl-dev
          - libreadline-dev
          - libcurl4-openssl-dev
          - docker-ce
          - heroku
          - openjdk-8-jdk

    - name: Add docker group
      user: name={{user}} append=yes groups=docker

    - name: Start services
      action: service name={{item}} state=started enabled=yes
      with_items:
        - mysql
        - postgresql
        - redis
        - docker
        - postgresql
        - chrony

    - name: Install awscli
      pip: name=awscli state=present

    - name: Install yarn
      npm: name=yarn global=yes state=present

    - name: Install docker-clean
      npm: name=docker-clean global=yes state=present

    - name: Install rbenv
      become_user: '{{user}}'
      git: repo=https://github.com/rbenv/rbenv.git dest=/home/{{user}}/.rbenv accept_hostkey=yes

    - name: Install ruby-build
      become_user: '{{user}}'
      git: repo=https://github.com/rbenv/ruby-build.git dest=/home/{{user}}/.rbenv/plugins/ruby-build accept_hostkey=yes

    - name: Install nodenv
      become_user: '{{user}}'
      git: repo=https://github.com/nodenv/nodenv.git dest=/home/{{user}}/.nodenv accept_hostkey=yes

    - name: Install node-build
      become_user: '{{user}}'
      git: repo=https://github.com/nodenv/node-build.git dest=/home/{{user}}/.nodenv/plugins/nodenv-build accept_hostkey=yes

    - name: Install embulk
      get_url:
        url: https://dl.embulk.org/embulk-latest.jar
        dest: /usr/local/bin/embulk
        mode: 0755

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Execute chsh zsh
      command: chsh {{user}} -s /bin/zsh

    - name: Execute git clone dotfiles
      become_user: '{{user}}'
      git: repo=https://github.com/f96q/dotfiles.git dest=/home/{{user}}/dotfiles accept_hostkey=yes

    - name: Setup dotfiles
      become_user: '{{user}}'
      command: bash setup.sh chdir=/home/{{user}}/dotfiles

    - name: Allow Empty mysql root password
      command: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"

    - name: Create postgresql vagrant user
      become_user: postgres
      postgresql_user:
        name: vagrant
        role_attr_flags: SUPERUSER,LOGIN
